<?php

namespace ML\TicketingBundle\Repository;

/**
 * OrderTicketingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderTicketingRepository extends \Doctrine\ORM\EntityRepository
{
}
