<?php

namespace ML\TicketingBundle\Repository;

/**
 * TicketingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketingRepository extends \Doctrine\ORM\EntityRepository
{
}
