# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.contains_alphanumeric_validator:
        class: ML\CoreBundle\Validator\Constraints\ContainsAlphanumericValidator
        tags:
            - { name: validator.constraint_validator }

    app.contains_hourly_validator:
            class: ML\CoreBundle\Validator\Constraints\HourlyValidator
            tags:
                - { name: validator.constraint_validator }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
